---
title: "Shiny_Final"
author: "Kaitlin Maciejewski"
date: "11/20/2017"
output: html_document
runtime: shiny
---

```{r setting up dataset, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(flexdashboard)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(forcats)
library(tidyverse)
library(plotly)
library(janitor)
library(shiny)


us_tweets <- read_csv("us_tweets_smaller.csv") 

#us_tweets$tweet_content_stripped <- gsub("[^[:alpha:] ]", "",
                                        # us_tweets$tweet_content) 

#us_tweets$tweet_content_stripped <- gsub(" *\\b[[:alpha:]]{1,2}\\b *", " ",
                                         #us_tweets$tweet_content_stripped) 


#getting state from latitude longitude data
state_tweets = us_tweets %>%
  select("longitude", "latitude")

library(sp)
library(maps)
library(maptools)
library(gpclib)
library(stringi)

latlong2state <- function(state_tweets) {
    states <- map('state', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    states_tweets_SP <- SpatialPoints(state_tweets, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))
    
    indices <- over(states_tweets_SP, states_sp)

    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stateNames[indices]
}


us_tweets$state_name <- stri_trans_totitle(latlong2state(state_tweets))
```

```{r, decreasing missingness, include = FALSE}

#PARSING TO DECREASE STATE MISSINGNESS
us_tweets = us_tweets %>%
  filter(country == "US") %>%
  mutate(state = str_sub(place_as_appears_on_bio, start = -2), state = trimws(state)) 

#formatting place that was state, USA
state_fix = us_tweets %>%
  filter(state == "SA") %>%
  mutate(fixed_state = NA)


list = strsplit(state_fix$place_as_appears_on_bio, split=',', fixed=TRUE)
df <- plyr::ldply(list)
colnames(df) <- c("State", "USA")

#state name
state_fix = state_fix %>%
  mutate(state = trimws(state), fixed_state = df$State, fixed_state = trimws(fixed_state)) %>%
  mutate(fixed_state = state.abb[match(fixed_state,state.name)]) %>%
  mutate(fixed_state = state.name[match(fixed_state,state.abb)])

#add district of columbia
state_fix$fixed_state[is.na(state_fix$fixed_state)] <- "District of Columbia"

#fix SA of USA to be NA
us_tweets$state[us_tweets$state == "SA"] <- NA

#join datasets and ifelse to keep state name for most comprehensive set
us_tweets = full_join(us_tweets, state_fix)%>%
  mutate(updated_state = ifelse(is.na(state), fixed_state, state)) %>%
  mutate(updated_state = state.name[match(updated_state,state.abb)]) %>%
  mutate(updated2_state = ifelse(is.na(fixed_state), updated_state,
                                 fixed_state)) %>%
  select(-state, -fixed_state, -updated_state) %>%
  mutate(final_state = ifelse(is.na(state_name), updated2_state,
                                 state_name)) %>%
  select(-state_name, -updated2_state)
  



```

```{r, further tidying, include = FALSE}

#tidy: long form
us_tweets_long <- gather(us_tweets, key = sentiment, value = count, anger:trust, factor_key = TRUE)
 

#dataset to plot
tweets_shiny = us_tweets_long %>%
  filter(country == "US") %>%
  mutate(sentiment = as.character(sentiment)) %>%
  drop_na(final_state)

##overlaying points onto state map
#load us map data
all_states <- map_data("state")
all_states$region = Hmisc::capitalize(all_states$region)


#subsetting to get state specific
state1 <- subset(all_states, region == input$state_choice1)
state2 <- subest(al_states, region == onpit$state_choice2)

plot = ggplot() + geom_polygon(data = states, aes(x=long, y=lat, group = group),colour="white", fill="grey10" ) + geom_point( data=tweets_shiny, aes(x=longitude, y=latitude, color = sentiment, size = .1))

#subetting to state choice
tweet_state1 = tweets_shiny %>%
  filter(count > 0, final_state == input$state_choice1) %>%
  
```


```{r sentiment by state, echo=FALSE}
which_state = tweets_shiny %>% distinct(final_state) %>% 
  pull() %>% as.character() %>% sort()


# selectInput widget
selectInput("state_choice1", label = h3("Select first state"),
            choices = which_state, selected = "New York")

renderPlotly({
    tweets_shiny %>%
    filter(count > 0, final_state == input$state_choice1)%>%
  mutate(text_label = str_c("sentiment: ", sentiment, '\nlocation: ', place_as_appears_on_bio)) %>%
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~sentiment, text = ~text_label)
})



renderPlotly({
    tweets_shiny %>%
    filter(count > 0, final_state == input$state_choice1)%>%
  mutate(text_label = str_c("sentiment: ", sentiment, '\nlocation: ', place_as_appears_on_bio)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~sentiment, text = ~text_label)
})



######BAR PLOT FOR STATE 1 INPUT#######
renderPlotly({
  tweets = tweets_shiny %>%
  filter(final_state == "California")%>%
  group_by(sentiment) %>%
  summarize(sent_count = sum(count)) %>%
  mutate(sentiment = as.factor(sentiment), sentiment = fct_reorder(sentiment, sent_count, .desc = TRUE))%>%
  arrange(sent_count) %>%
  top_n(15) %>%
  plot_ly(x = ~sentiment, y = ~sent_count, type = "bar", color = ~sentiment)
})




renderPlotly({
  ggplotly() + geom_polygon(data = state1, aes(x=long, y=lat, group = group),colour="white", fill="grey10" ) + geom_point( data=tweet_state1, aes(x=longitude, y=latitude, color = sentiment, size = .01))
})
```


